"""Migration round-trip and drift checks.

These run the real Alembic command API against a scratch database, so what is tested
is the migration as Alembic actually applies it — not a reconstruction of it. Three
things are asserted:

* `upgrade head` produces the schema the models describe.
* Autogenerate against that migrated schema reports **no** differences. This is the
  drift check: without it, a model change that never made it into a migration is
  invisible until it reaches production, and a model/DDL disagreement that makes
  autogenerate churn shows up as a spurious drop-and-recreate in someone else's
  migration.
* `downgrade base` removes everything the upgrade created, and the upgrade can then
  run again. Native enum types are the trap here: they outlive the tables that used
  them, so a downgrade that forgets to drop them leaves the next upgrade failing on
  "type already exists".

A scratch database is used rather than the shared test database because these tests
drop and recreate the entire schema, which would race with any other test.
"""

from collections.abc import Iterator
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import Engine, create_engine, text
from sqlalchemy.engine import make_url

from app.core.config import get_settings

pytestmark = pytest.mark.integration

BACKEND_ROOT = Path(__file__).resolve().parents[2]

# Named with the `_test` suffix so the guard in `migration_database` recognises it as
# a test database. The name is a hard-coded constant, never user input, which is why
# it is safe to interpolate into the DDL below (CREATE DATABASE cannot take a
# parameter).
SCRATCH_DATABASE = "supportflow_migrations_test"

# 15 models plus alembic_version.
EXPECTED_TABLE_COUNT = 16

# The 13 StrEnum classes in app/models/enums.py.
EXPECTED_ENUM_TYPE_COUNT = 13


def _alembic_config(db_url: str) -> Config:
    """Alembic config aimed at `db_url`.

    The URL travels via `config.attributes` rather than `sqlalchemy.url`, because
    `set_main_option` runs the value through configparser's `%` interpolation — which
    a password containing a percent sign would break. It is also the channel env.py
    documents for programmatic callers.
    """
    config = Config(str(BACKEND_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(BACKEND_ROOT / "alembic"))
    config.attributes["db_url"] = db_url
    return config


def _public_tables(engine: Engine) -> set[str]:
    with engine.connect() as connection:
        rows = connection.execute(
            text(
                "SELECT table_name FROM information_schema.tables "
                "WHERE table_schema = 'public' AND table_type = 'BASE TABLE'"
            )
        )
        return {str(row[0]) for row in rows}


def _enum_types(engine: Engine) -> set[str]:
    with engine.connect() as connection:
        rows = connection.execute(
            text(
                "SELECT t.typname FROM pg_type t "
                "JOIN pg_namespace n ON n.oid = t.typnamespace "
                "WHERE n.nspname = 'public' AND t.typtype = 'e'"
            )
        )
        return {str(row[0]) for row in rows}


@pytest.fixture(scope="module")
def migration_database() -> Iterator[str]:
    """A scratch database, empty and extension-free, dropped afterwards.

    Deliberately created without `CREATE EXTENSION`: the baseline migration is
    expected to install `vector` and `pg_trgm` itself, and a database that already
    had them would hide it if it did not.
    """
    url = make_url(get_settings().sqlalchemy_dsn)

    if not (url.database or "").endswith("_test"):
        pytest.fail(
            f"refusing to run destructive migration tests against {url.database!r}; "
            "the database name must end with '_test'"
        )

    scratch_url = url.set(database=SCRATCH_DATABASE)

    # CREATE DATABASE cannot run inside a transaction, hence AUTOCOMMIT.
    admin_engine = create_engine(url.set(database="postgres"), isolation_level="AUTOCOMMIT")
    try:
        with admin_engine.connect() as connection:
            # WITH (FORCE) disconnects anything still attached. Without it a leaked
            # connection from a previous failed run blocks the drop, and the failure
            # looks like a permissions error.
            connection.execute(text(f'DROP DATABASE IF EXISTS "{SCRATCH_DATABASE}" WITH (FORCE)'))
            connection.execute(text(f'CREATE DATABASE "{SCRATCH_DATABASE}"'))

        yield scratch_url.render_as_string(hide_password=False)
    finally:
        with admin_engine.connect() as connection:
            connection.execute(text(f'DROP DATABASE IF EXISTS "{SCRATCH_DATABASE}" WITH (FORCE)'))
        admin_engine.dispose()


@pytest.fixture
def upgraded_database(migration_database: str) -> Iterator[tuple[str, Engine]]:
    """A scratch database taken to head, and an engine pointed at it."""
    command.upgrade(_alembic_config(migration_database), "head")
    engine = create_engine(migration_database)
    try:
        yield migration_database, engine
    finally:
        engine.dispose()


def test_upgrade_creates_every_table(upgraded_database: tuple[str, Engine]) -> None:
    _, engine = upgraded_database
    tables = _public_tables(engine)

    assert len(tables) == EXPECTED_TABLE_COUNT, f"unexpected tables: {sorted(tables)}"
    # Spot-check one table from each end of the dependency graph, so a migration that
    # created tables in a broken order could not pass by count alone.
    assert {"organizations", "tickets", "knowledge_chunks", "alembic_version"} <= tables


def test_upgrade_creates_every_enum_type(upgraded_database: tuple[str, Engine]) -> None:
    _, engine = upgraded_database
    assert len(_enum_types(engine)) == EXPECTED_ENUM_TYPE_COUNT


def test_upgrade_installs_the_extensions_the_schema_needs(
    upgraded_database: tuple[str, Engine],
) -> None:
    """The migration is self-sufficient on a database that has neither extension.

    `vector` backs the knowledge_chunks embedding column and `pg_trgm` the customer
    search indexes, so a missing extension is not a cosmetic problem — the DDL that
    needs them cannot have run at all. The fixture creates the database without
    either, so the assertion is that the migration installed them.
    """
    _, engine = upgraded_database
    with engine.connect() as connection:
        installed = {
            str(row[0]) for row in connection.execute(text("SELECT extname FROM pg_extension"))
        }

    assert {"vector", "pg_trgm"} <= installed


def test_autogenerate_reports_no_drift(upgraded_database: tuple[str, Engine]) -> None:
    """The drift check: models and the migrated schema agree.

    `command.check` raises AutogenerateDiffsDetected when autogenerate would produce
    operations, and prints nothing otherwise. It is the only assertion here that
    couples the models to the migration — every other test inspects the database.
    """
    db_url, _ = upgraded_database
    config = _alembic_config(db_url)

    try:
        command.check(config)
    except AutogenerateDiffsDetected as exc:
        pytest.fail(
            "models and the migrated schema have diverged — run "
            f"`alembic revision --autogenerate` and commit the result:\n{exc}"
        )


def test_downgrade_removes_the_schema_and_its_enum_types(
    upgraded_database: tuple[str, Engine],
) -> None:
    """`downgrade base` leaves no tables and, crucially, no enum types.

    A leftover enum type is the failure that makes this test worth having: it does
    not show up here, it shows up as the *next* upgrade failing.
    """
    db_url, engine = upgraded_database
    command.downgrade(_alembic_config(db_url), "base")

    with engine.connect() as connection:
        connection.execute(text("COMMIT"))  # end any implicit read transaction

    assert _public_tables(engine) == {"alembic_version"}
    assert _enum_types(engine) == set()


def test_upgrade_is_repeatable_after_a_downgrade(upgraded_database: tuple[str, Engine]) -> None:
    """upgrade → downgrade → upgrade is a clean round-trip.

    This is the assertion that catches a downgrade which drops tables but not the
    types they used: the second upgrade fails with "type already exists in schema".
    """
    db_url, engine = upgraded_database
    config = _alembic_config(db_url)

    command.downgrade(config, "base")
    command.upgrade(config, "head")

    assert len(_public_tables(engine)) == EXPECTED_TABLE_COUNT
    assert len(_enum_types(engine)) == EXPECTED_ENUM_TYPE_COUNT
