"""Migration round-trip and drift checks.

These run the real Alembic command API against a scratch database, so what is tested
is the migration as Alembic actually applies it — not a reconstruction of it. Three
things are asserted:

* `upgrade head` produces the schema the models describe.
* Autogenerate against that migrated schema reports **no** differences. This is the
  drift check: without it, a model change that never made it into a migration is
  invisible until it reaches production, and a model/DDL disagreement that makes
  autogenerate churn shows up as a spurious drop-and-recreate in someone else's
  migration.
* `downgrade base` removes everything the upgrade created, and the upgrade can then
  run again. Native enum types are the trap here: they outlive the tables that used
  them, so a downgrade that forgets to drop them leaves the next upgrade failing on
  "type already exists".

A scratch database is used rather than the shared test database because these tests
drop and recreate the entire schema, which would race with any other test.
"""

from collections.abc import Iterator
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import Engine, create_engine, text
from sqlalchemy.engine import make_url

from app.core.config import get_settings

pytestmark = pytest.mark.integration

BACKEND_ROOT = Path(__file__).resolve().parents[2]

# Named with the `_test` suffix so the guard in `migration_database` recognises it as
# a test database. The name is a hard-coded constant, never user input, which is why
# it is safe to interpolate into the DDL below (CREATE DATABASE cannot take a
# parameter).
SCRATCH_DATABASE = "supportflow_migrations_test"

# 15 models plus alembic_version.
EXPECTED_TABLE_COUNT = 16

# The 13 StrEnum classes in app/models/enums.py.
EXPECTED_ENUM_TYPE_COUNT = 13


def _alembic_config(db_url: str) -> Config:
    """Alembic config aimed at `db_url`.

    The URL travels via `config.attributes` rather than `sqlalchemy.url`, because
    `set_main_option` runs the value through configparser's `%` interpolation — which
    a password containing a percent sign would break. It is also the channel env.py
    documents for programmatic callers.
    """
    config = Config(str(BACKEND_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(BACKEND_ROOT / "alembic"))
    config.attributes["db_url"] = db_url
    return config


def _public_tables(engine: Engine) -> set[str]:
    with engine.connect() as connection:
        rows = connection.execute(
            text(
                "SELECT table_name FROM information_schema.tables "
                "WHERE table_schema = 'public' AND table_type = 'BASE TABLE'"
            )
        )
        return {str(row[0]) for row in rows}


def _enum_types(engine: Engine) -> set[str]:
    with engine.connect() as connection:
        rows = connection.execute(
            text(
                "SELECT t.typname FROM pg_type t "
                "JOIN pg_namespace n ON n.oid = t.typnamespace "
                "WHERE n.nspname = 'public' AND t.typtype = 'e'"
            )
        )
        return {str(row[0]) for row in rows}


@pytest.fixture(scope="module")
def migration_database() -> Iterator[str]:
    """A scratch database, empty and extension-free, dropped afterwards.

    Deliberately created without `CREATE EXTENSION`: the baseline migration is
    expected to install `vector` and `pg_trgm` itself, and a database that already
    had them would hide it if it did not.
    """
    url = make_url(get_settings().sqlalchemy_dsn)

    if not (url.database or "").endswith("_test"):
        pytest.fail(
            f"refusing to run destructive migration tests against {url.database!r}; "
            "the database name must end with '_test'"
        )

    scratch_url = url.set(database=SCRATCH_DATABASE)

    # CREATE DATABASE cannot run inside a transaction, hence AUTOCOMMIT.
    admin_engine = create_engine(url.set(database="postgres"), isolation_level="AUTOCOMMIT")
    try:
        with admin_engine.connect() as connection:
            # WITH (FORCE) disconnects anything still attached. Without it a leaked
            # connection from a previous failed run blocks the drop, and the failure
            # looks like a permissions error.
            connection.execute(text(f'DROP DATABASE IF EXISTS "{SCRATCH_DATABASE}" WITH (FORCE)'))
            connection.execute(text(f'CREATE DATABASE "{SCRATCH_DATABASE}"'))

        yield scratch_url.render_as_string(hide_password=False)
    finally:
        with admin_engine.connect() as connection:
            connection.execute(text(f'DROP DATABASE IF EXISTS "{SCRATCH_DATABASE}" WITH (FORCE)'))
        admin_engine.dispose()


@pytest.fixture
def upgraded_database(migration_database: str) -> Iterator[tuple[str, Engine]]:
    """A scratch database taken to head, and an engine pointed at it."""
    command.upgrade(_alembic_config(migration_database), "head")
    engine = create_engine(migration_database)
    try:
        yield migration_database, engine
    finally:
        engine.dispose()


def test_upgrade_creates_every_table(upgraded_database: tuple[str, Engine]) -> None:
    _, engine = upgraded_database
    tables = _public_tables(engine)

    assert len(tables) == EXPECTED_TABLE_COUNT, f"unexpected tables: {sorted(tables)}"
    # Spot-check one table from each end of the dependency graph, so a migration that
    # created tables in a broken order could not pass by count alone.
    assert {"organizations", "tickets", "knowledge_chunks", "alembic_version"} <= tables


def test_upgrade_creates_every_enum_type(upgraded_database: tuple[str, Engine]) -> None:
    _, engine = upgraded_database
    assert len(_enum_types(engine)) == EXPECTED_ENUM_TYPE_COUNT


def test_upgrade_installs_the_extensions_the_schema_needs(
    upgraded_database: tuple[str, Engine],
) -> None:
    """The migration is self-sufficient on a database that has neither extension.

    `vector` backs the knowledge_chunks embedding column and `pg_trgm` the customer
    search indexes, so a missing extension is not a cosmetic problem — the DDL that
    needs them cannot have run at all. The fixture creates the database without
    either, so the assertion is that the migration installed them.
    """
    _, engine = upgraded_database
    with engine.connect() as connection:
        installed = {
            str(row[0]) for row in connection.execute(text("SELECT extname FROM pg_extension"))
        }

    assert {"vector", "pg_trgm"} <= installed


def test_autogenerate_reports_no_drift(upgraded_database: tuple[str, Engine]) -> None:
    """The drift check: models and the migrated schema agree.

    `command.check` raises AutogenerateDiffsDetected when autogenerate would produce
    operations, and prints nothing otherwise. It is the only assertion here that
    couples the models to the migration — every other test inspects the database.
    """
    db_url, _ = upgraded_database
    config = _alembic_config(db_url)

    try:
        command.check(config)
    except AutogenerateDiffsDetected as exc:
        pytest.fail(
            "models and the migrated schema have diverged — run "
            f"`alembic revision --autogenerate` and commit the result:\n{exc}"
        )


def test_downgrade_removes_the_schema_and_its_enum_types(
    upgraded_database: tuple[str, Engine],
) -> None:
    """`downgrade base` leaves no tables and, crucially, no enum types.

    A leftover enum type is the failure that makes this test worth having: it does
    not show up here, it shows up as the *next* upgrade failing.
    """
    db_url, engine = upgraded_database
    command.downgrade(_alembic_config(db_url), "base")

    with engine.connect() as connection:
        connection.execute(text("COMMIT"))  # end any implicit read transaction

    assert _public_tables(engine) == {"alembic_version"}
    assert _enum_types(engine) == set()


def test_upgrade_is_repeatable_after_a_downgrade(upgraded_database: tuple[str, Engine]) -> None:
    """upgrade → downgrade → upgrade is a clean round-trip.

    This is the assertion that catches a downgrade which drops tables but not the
    types they used: the second upgrade fails with "type already exists in schema".
    """
    db_url, engine = upgraded_database
    config = _alembic_config(db_url)

    command.downgrade(config, "base")
    command.upgrade(config, "head")

    assert len(_public_tables(engine)) == EXPECTED_TABLE_COUNT
    assert len(_enum_types(engine)) == EXPECTED_ENUM_TYPE_COUNT


# The revision that adds `ix_messages_fts`, Phase N's index over the message body.
MESSAGE_FTS_REVISION = "e672102955a8"

# The revision that adds `notifications.emailed_at`, Phase P's delivery marker.
EMAILED_AT_REVISION = "a49a5939bf77"


def _index_exists(engine: Engine, name: str) -> bool:
    with engine.connect() as connection:
        return (
            connection.execute(
                text("SELECT 1 FROM pg_class WHERE relname = :name AND relkind = 'i'"),
                {"name": name},
            ).one_or_none()
            is not None
        )


def _column_exists(engine: Engine, table: str, column: str) -> bool:
    with engine.connect() as connection:
        return (
            connection.execute(
                text(
                    "SELECT 1 FROM information_schema.columns "
                    "WHERE table_schema = 'public' "
                    "AND table_name = :table AND column_name = :column"
                ),
                {"table": table, "column": column},
            ).one_or_none()
            is not None
        )


def _walk_down_to(config: Config, revision: str) -> str:
    """Take the database to `revision` and return its parent, for a one-step descent.

    Walks *down* to the revision instead of requiring it to be head. The previous version
    of this file pinned `head` and failed loudly when a newer migration landed, with a
    message telling the next person to repoint the test at the new head. That is the wrong
    arc: the property under test is "this revision's `downgrade()` undoes this revision",
    and it is true no matter how many migrations come after it. Pinning the head meant
    every phase broke a test about an older phase's index, and the suggested repair would
    have quietly moved the test off the thing it was written to check.

    Descending from wherever the database is also means the assertions below run against a
    database that reached this revision the normal way, with everything underneath already
    applied.
    """
    script = ScriptDirectory.from_config(config)
    command.downgrade(config, revision)
    previous = script.get_revision(revision).down_revision
    assert isinstance(previous, str), "this revision is expected to have a single parent"
    return previous


def test_the_message_fts_migration_downgrades_on_its_own(
    upgraded_database: tuple[str, Engine],
) -> None:
    """One revision down removes exactly its index, and one back up restores it.

    The other downgrade test goes all the way to `base`, which cannot catch a
    `downgrade()` that forgets its `drop_index`: dropping the table takes its indexes
    with it, so every per-revision downgrade bug is invisible from `base`. A single
    step is the only place that assertion can be made.
    """
    db_url, engine = upgraded_database
    config = _alembic_config(db_url)
    previous = _walk_down_to(config, MESSAGE_FTS_REVISION)

    assert _index_exists(engine, "ix_messages_fts"), "the revision did not create the index"

    command.downgrade(config, previous)
    assert not _index_exists(engine, "ix_messages_fts"), "the downgrade left the index behind"

    command.upgrade(config, "head")
    assert _index_exists(engine, "ix_messages_fts"), "the re-upgrade did not restore the index"


def test_the_emailed_at_migration_downgrades_on_its_own(
    upgraded_database: tuple[str, Engine],
) -> None:
    """Phase P's migration, held to the same single-step property.

    A nullable column is the easiest possible thing to add and the easiest to forget to
    remove: `downgrade()` with no `drop_column` in it leaves the column on the table, and
    because it is nullable nothing breaks — the schema simply stops matching the revision
    it claims to be at, and the next `upgrade` fails on "column already exists". Going to
    `base` and back cannot see it, for the same reason the index test above gives.
    """
    db_url, engine = upgraded_database
    config = _alembic_config(db_url)
    previous = _walk_down_to(config, EMAILED_AT_REVISION)

    assert _column_exists(engine, "notifications", "emailed_at"), "the revision added no column"

    command.downgrade(config, previous)
    assert not _column_exists(engine, "notifications", "emailed_at"), (
        "the downgrade left the column behind"
    )

    command.upgrade(config, "head")
    assert _column_exists(engine, "notifications", "emailed_at"), (
        "the re-upgrade did not restore it"
    )
