"""baseline schema

Creates the complete SupportFlow schema: 15 tables, 13 native enum types, and every
index and constraint declared in app/models.

Generated by `alembic revision --autogenerate` against an empty database, then
hand-edited in three places — each marked with a HAND-EDIT comment below:

1. The `vector` and `pg_trgm` extensions are created explicitly. Autogenerate does
   not manage extensions, so without this the migration only works on a database
   where something else already installed them.
2. `pgvector` is imported. Autogenerate emits the fully-qualified
   `pgvector.sqlalchemy.vector.VECTOR` type without emitting its import, so the
   generated file raises NameError the moment it runs.
3. The 13 enum types are dropped explicitly on downgrade. `op.drop_table` does not
   drop the enum types a table used, so without this a `downgrade base` leaves them
   behind and the next `upgrade head` fails with "type already exists".

`ix_tickets_fts` was also rewritten to the expression PostgreSQL stores rather than
the one autogenerate copied out of the model, so that the migration and the model
agree verbatim. See that index in app/models/ticket.py for why it matters.

Revision ID: bd8e646eeff8
Revises:
Create Date: 2026-09-11 20:27:20.854638

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# HAND-EDIT (2): required by the `embedding` column below; see module docstring.
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bd8e646eeff8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the schema."""
    # HAND-EDIT (1): the extensions this schema depends on. Must run first —
    # `vector` supplies the type for knowledge_chunks.embedding, `pg_trgm` the
    # gin_trgm_ops operator class for the customer search indexes.
    #
    # IF NOT EXISTS because the docker entrypoint already installs these on a dev
    # database, and a re-run must not fail. uuid-ossp is absent deliberately:
    # gen_random_uuid() is core since PostgreSQL 13 and needs no extension.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column(
            "plan",
            sa.Enum("free", "pro", "enterprise", name="organization_plan"),
            server_default="free",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("active", "suspended", name="organization_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_index(op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True)
    op.create_index(op.f("ix_organizations_status"), "organizations", ["status"], unique=False)
    op.create_table(
        "customers",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("external_reference", sa.String(length=200), nullable=True),
        sa.Column(
            "extra_data",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_customers_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint(
            "organization_id", "email", name=op.f("uq_customers_organization_id_email")
        ),
    )
    op.create_index(op.f("ix_customers_email"), "customers", ["email"], unique=False)
    op.create_index(
        "ix_customers_email_trgm",
        "customers",
        ["email"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"email": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("ix_customers_external_reference"), "customers", ["external_reference"], unique=False
    )
    op.create_index(
        "ix_customers_name_trgm",
        "customers",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_table(
        "sla_policies",
        sa.Column(
            "priority",
            sa.Enum("low", "medium", "high", "urgent", name="ticket_priority"),
            nullable=False,
        ),
        sa.Column("response_time_minutes", sa.Integer(), nullable=False),
        sa.Column("resolution_time_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "warning_threshold_percent", sa.Integer(), server_default=sa.text("80"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "resolution_time_minutes > 0", name=op.f("ck_sla_policies_resolution_time_positive")
        ),
        sa.CheckConstraint(
            "resolution_time_minutes >= response_time_minutes",
            name=op.f("ck_sla_policies_resolution_after_response"),
        ),
        sa.CheckConstraint(
            "response_time_minutes > 0", name=op.f("ck_sla_policies_response_time_positive")
        ),
        sa.CheckConstraint(
            "warning_threshold_percent > 0 AND warning_threshold_percent < 100",
            name=op.f("ck_sla_policies_warning_threshold_range"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_sla_policies_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sla_policies")),
        sa.UniqueConstraint(
            "organization_id", "priority", name=op.f("uq_sla_policies_organization_id_priority")
        ),
    )
    op.create_table(
        "users",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "manager", "agent", "customer", name="user_role"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_users_customer_id_customers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_users_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint(
            "organization_id", "email", name=op.f("uq_users_organization_id_email")
        ),
    )
    op.create_index(op.f("ix_users_customer_id"), "users", ["customer_id"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column(
            "action",
            sa.Enum(
                "user_created",
                "user_role_updated",
                "user_deactivated",
                "ticket_created",
                "ticket_assigned",
                "ticket_priority_changed",
                "ticket_status_changed",
                "ticket_resolved",
                "ticket_reopened",
                "knowledge_document_created",
                "knowledge_document_deleted",
                "ai_analysis_requested",
                "ai_response_accepted",
                "ai_response_regenerated",
                "sla_policy_updated",
                "organization_updated",
                name="audit_action",
            ),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_email", sa.String(length=320), nullable=True),
        sa.Column("target_type", sa.String(length=50), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=True),
        sa.Column(
            "extra_data",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_audit_logs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        "ix_audit_logs_org_action_created",
        "audit_logs",
        ["organization_id", "action", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_logs_org_actor_created",
        "audit_logs",
        ["organization_id", "actor_user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_logs_org_created", "audit_logs", ["organization_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_audit_logs_target",
        "audit_logs",
        ["organization_id", "target_type", "target_id"],
        unique=False,
    )
    op.create_table(
        "knowledge_documents",
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("upload", "url", "manual", name="document_source_type"),
            nullable=False,
        ),
        sa.Column("source_reference", sa.String(length=1000), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "processing", "completed", "failed", name="processing_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("chunk_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_published", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_knowledge_documents_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_knowledge_documents_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_documents")),
    )
    op.create_index(
        "ix_knowledge_documents_org_published",
        "knowledge_documents",
        ["organization_id", "updated_at"],
        unique=False,
        postgresql_where=sa.text("is_published = true AND status = 'completed'"),
    )
    op.create_index(
        "ix_knowledge_documents_pending",
        "knowledge_documents",
        ["organization_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('pending', 'processing')"),
    )
    op.create_index(
        "ix_knowledge_documents_title_trgm",
        "knowledge_documents",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_id", sa.UUID(), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_refresh_tokens_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["refresh_tokens.id"],
            name=op.f("fk_refresh_tokens_replaced_by_id_refresh_tokens"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
    )
    op.create_index("ix_refresh_tokens_expires_at", "refresh_tokens", ["expires_at"], unique=False)
    op.create_index(
        op.f("ix_refresh_tokens_organization_id"),
        "refresh_tokens",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=True
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_index(
        "ix_refresh_tokens_user_id_revoked_at",
        "refresh_tokens",
        ["user_id", "revoked_at"],
        unique=False,
    )
    op.create_table(
        "tickets",
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("assigned_agent_id", sa.UUID(), nullable=True),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "assigned",
                "in_progress",
                "waiting_for_customer",
                "resolved",
                "closed",
                name="ticket_status",
            ),
            server_default="open",
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("low", "medium", "high", "urgent", name="ticket_priority"),
            server_default="medium",
            nullable=False,
        ),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("subcategory", sa.String(length=100), nullable=True),
        sa.Column(
            "sentiment", sa.Enum("positive", "neutral", "negative", name="sentiment"), nullable=True
        ),
        sa.Column("sentiment_confidence", sa.Float(), nullable=True),
        sa.Column(
            "ai_recommended_priority",
            sa.Enum("low", "medium", "high", "urgent", name="ticket_priority"),
            nullable=True,
        ),
        sa.Column("ai_priority_score", sa.Float(), nullable=True),
        sa.Column("ai_classification_confidence", sa.Float(), nullable=True),
        sa.Column("first_response_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'resolved' AND resolved_at IS NOT NULL) OR (status = 'closed' AND resolved_at IS NOT NULL) OR (status NOT IN ('resolved', 'closed'))",
            name=op.f("ck_tickets_resolved_at_matches_status"),
        ),
        sa.CheckConstraint(
            "ai_classification_confidence IS NULL OR (ai_classification_confidence >= 0 AND ai_classification_confidence <= 1)",
            name=op.f("ck_tickets_ai_classification_confidence_range"),
        ),
        sa.CheckConstraint(
            "sentiment_confidence IS NULL OR (sentiment_confidence >= 0 AND sentiment_confidence <= 1)",
            name=op.f("ck_tickets_sentiment_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_agent_id"],
            ["users.id"],
            name=op.f("fk_tickets_assigned_agent_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_tickets_customer_id_customers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_tickets_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tickets")),
    )
    op.create_index(
        "ix_tickets_fts",
        "tickets",
        [
            sa.literal_column(
                "to_tsvector('english'::regconfig, (subject::text || ' '::text) || description)"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_tickets_org_agent_status_created",
        "tickets",
        ["organization_id", "assigned_agent_id", "status", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_tickets_org_category", "tickets", ["organization_id", "category"], unique=False
    )
    op.create_index(
        "ix_tickets_org_created_at", "tickets", ["organization_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_tickets_org_customer_created",
        "tickets",
        ["organization_id", "customer_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_tickets_org_status_priority",
        "tickets",
        ["organization_id", "status", "priority"],
        unique=False,
    )
    op.create_index(
        "ix_tickets_sla_pending",
        "tickets",
        ["organization_id", "priority", "created_at"],
        unique=False,
        postgresql_where=sa.text("status NOT IN ('resolved', 'closed')"),
    )
    op.create_index("uq_tickets_org_number", "tickets", ["organization_id", "number"], unique=True)
    op.create_table(
        "ai_analyses",
        sa.Column("ticket_id", sa.UUID(), nullable=False),
        sa.Column(
            "operation",
            sa.Enum(
                "classify",
                "sentiment",
                "summarize",
                "suggest_response",
                "embed",
                "knowledge_answer",
                name="ai_operation",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "processing", "completed", "failed", name="processing_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "result", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'completed' AND result IS NOT NULL AND result <> 'null'::jsonb) OR (status = 'failed' AND error_message IS NOT NULL) OR status IN ('pending', 'processing')",
            name=op.f("ck_ai_analyses_terminal_status_has_payload"),
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_ai_analyses_confidence_range"),
        ),
        sa.CheckConstraint(
            "latency_ms IS NULL OR latency_ms >= 0",
            name=op.f("ck_ai_analyses_latency_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_ai_analyses_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
            name=op.f("fk_ai_analyses_ticket_id_tickets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_analyses")),
    )
    op.create_index(
        "ix_ai_analyses_pending",
        "ai_analyses",
        ["organization_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('pending', 'processing')"),
    )
    op.create_index(
        "ix_ai_analyses_ticket_operation_created",
        "ai_analyses",
        ["ticket_id", "operation", "created_at"],
        unique=False,
    )
    op.create_table(
        "ai_usage",
        sa.Column(
            "operation",
            sa.Enum(
                "classify",
                "sentiment",
                "summarize",
                "suggest_response",
                "embed",
                "knowledge_answer",
                name="ai_operation",
            ),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "cost_usd",
            sa.Numeric(precision=12, scale=6),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("ticket_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("was_successful", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("was_cached", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "completion_tokens >= 0", name=op.f("ck_ai_usage_completion_tokens_non_negative")
        ),
        sa.CheckConstraint("cost_usd >= 0", name=op.f("ck_ai_usage_cost_non_negative")),
        sa.CheckConstraint(
            "prompt_tokens >= 0", name=op.f("ck_ai_usage_prompt_tokens_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_ai_usage_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
            name=op.f("fk_ai_usage_ticket_id_tickets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_ai_usage_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_usage")),
    )
    op.create_index(
        "ix_ai_usage_org_created", "ai_usage", ["organization_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_ai_usage_org_operation_created",
        "ai_usage",
        ["organization_id", "operation", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_ai_usage_org_user_created",
        "ai_usage",
        ["organization_id", "user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "knowledge_chunks",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(dim=1536), nullable=True),
        sa.Column("embedding_model", sa.String(length=100), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "chunk_index >= 0", name=op.f("ck_knowledge_chunks_chunk_index_non_negative")
        ),
        sa.CheckConstraint(
            "token_count > 0", name=op.f("ck_knowledge_chunks_token_count_positive")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["knowledge_documents.id"],
            name=op.f("fk_knowledge_chunks_document_id_knowledge_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_knowledge_chunks_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_chunks")),
        sa.UniqueConstraint(
            "document_id", "chunk_index", name=op.f("uq_knowledge_chunks_document_id_chunk_index")
        ),
    )
    op.create_index(
        "ix_knowledge_chunks_embedding_hnsw",
        "knowledge_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_knowledge_chunks_org_document",
        "knowledge_chunks",
        ["organization_id", "document_id"],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("ticket_id", sa.UUID(), nullable=False),
        sa.Column(
            "sender_type",
            sa.Enum("customer", "agent", "system", "ai_draft", name="sender_type"),
            nullable=False,
        ),
        sa.Column("sender_user_id", sa.UUID(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_internal", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT (is_internal AND sender_type = 'customer')",
            name=op.f("ck_messages_internal_note_not_from_customer"),
        ),
        sa.CheckConstraint(
            "sender_type <> 'ai_draft' OR is_internal",
            name=op.f("ck_messages_ai_draft_is_internal"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_messages_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sender_user_id"],
            ["users.id"],
            name=op.f("fk_messages_sender_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
            name=op.f("fk_messages_ticket_id_tickets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index(
        op.f("ix_messages_organization_id"), "messages", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_messages_ticket_created", "messages", ["ticket_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_messages_ticket_public_created",
        "messages",
        ["ticket_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("is_internal = false"),
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "notification_type",
            sa.Enum(
                "ticket_assigned",
                "ticket_reassigned",
                "new_customer_reply",
                "mention",
                "sla_warning",
                "ai_analysis_completed",
                "ticket_resolved",
                name="notification_type",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.String(length=1000), nullable=False),
        sa.Column("ticket_id", sa.UUID(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_notifications_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
            name=op.f("fk_notifications_ticket_id_tickets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        op.f("ix_notifications_organization_id"), "notifications", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_ticket_id"), "notifications", ["ticket_id"], unique=False
    )
    op.create_index(
        "ix_notifications_user_created", "notifications", ["user_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_notifications_user_unread",
        "notifications",
        ["user_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("read_at IS NULL"),
    )
    op.create_table(
        "ticket_events",
        sa.Column("ticket_id", sa.UUID(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "created",
                "assigned",
                "unassigned",
                "status_changed",
                "priority_changed",
                "message_added",
                "internal_note_added",
                "attachment_added",
                "ai_analysis_completed",
                "sla_warning",
                "sla_breached",
                "reopened",
                name="ticket_event_type",
            ),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("from_value", sa.String(length=100), nullable=True),
        sa.Column("to_value", sa.String(length=100), nullable=True),
        sa.Column(
            "extra_data",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_ticket_events_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_ticket_events_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
            name=op.f("fk_ticket_events_ticket_id_tickets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ticket_events")),
    )
    op.create_index(
        op.f("ix_ticket_events_organization_id"), "ticket_events", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_ticket_events_ticket_created",
        "ticket_events",
        ["ticket_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "attachments",
        sa.Column("ticket_id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=True),
        sa.Column("uploaded_by_id", sa.UUID(), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_attachments_size_bytes_positive")),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_attachments_message_id_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_attachments_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
            name=op.f("fk_attachments_ticket_id_tickets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["users.id"],
            name=op.f("fk_attachments_uploaded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachments")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_attachments_storage_key")),
    )
    op.create_index(op.f("ix_attachments_message_id"), "attachments", ["message_id"], unique=False)
    op.create_index(
        op.f("ix_attachments_organization_id"), "attachments", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_attachments_ticket_created", "attachments", ["ticket_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision.

    Every migration in this project must be reversible, so that `upgrade head` then
    `downgrade base` is a clean round-trip. Dropping types and objects an upgrade
    created is part of the migration, not an afterthought.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_attachments_ticket_created", table_name="attachments")
    op.drop_index(op.f("ix_attachments_organization_id"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_message_id"), table_name="attachments")
    op.drop_table("attachments")
    op.drop_index("ix_ticket_events_ticket_created", table_name="ticket_events")
    op.drop_index(op.f("ix_ticket_events_organization_id"), table_name="ticket_events")
    op.drop_table("ticket_events")
    op.drop_index(
        "ix_notifications_user_unread",
        table_name="notifications",
        postgresql_where=sa.text("read_at IS NULL"),
    )
    op.drop_index("ix_notifications_user_created", table_name="notifications")
    op.drop_index(op.f("ix_notifications_ticket_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_organization_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(
        "ix_messages_ticket_public_created",
        table_name="messages",
        postgresql_where=sa.text("is_internal = false"),
    )
    op.drop_index("ix_messages_ticket_created", table_name="messages")
    op.drop_index(op.f("ix_messages_organization_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index("ix_knowledge_chunks_org_document", table_name="knowledge_chunks")
    op.drop_index(
        "ix_knowledge_chunks_embedding_hnsw",
        table_name="knowledge_chunks",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("knowledge_chunks")
    op.drop_index("ix_ai_usage_org_user_created", table_name="ai_usage")
    op.drop_index("ix_ai_usage_org_operation_created", table_name="ai_usage")
    op.drop_index("ix_ai_usage_org_created", table_name="ai_usage")
    op.drop_table("ai_usage")
    op.drop_index("ix_ai_analyses_ticket_operation_created", table_name="ai_analyses")
    op.drop_index(
        "ix_ai_analyses_pending",
        table_name="ai_analyses",
        postgresql_where=sa.text("status IN ('pending', 'processing')"),
    )
    op.drop_table("ai_analyses")
    op.drop_index("uq_tickets_org_number", table_name="tickets")
    op.drop_index(
        "ix_tickets_sla_pending",
        table_name="tickets",
        postgresql_where=sa.text("status NOT IN ('resolved', 'closed')"),
    )
    op.drop_index("ix_tickets_org_status_priority", table_name="tickets")
    op.drop_index("ix_tickets_org_customer_created", table_name="tickets")
    op.drop_index("ix_tickets_org_created_at", table_name="tickets")
    op.drop_index("ix_tickets_org_category", table_name="tickets")
    op.drop_index("ix_tickets_org_agent_status_created", table_name="tickets")
    op.drop_index("ix_tickets_fts", table_name="tickets", postgresql_using="gin")
    op.drop_table("tickets")
    op.drop_index("ix_refresh_tokens_user_id_revoked_at", table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_organization_id"), table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_expires_at", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(
        "ix_knowledge_documents_title_trgm",
        table_name="knowledge_documents",
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_knowledge_documents_pending",
        table_name="knowledge_documents",
        postgresql_where=sa.text("status IN ('pending', 'processing')"),
    )
    op.drop_index(
        "ix_knowledge_documents_org_published",
        table_name="knowledge_documents",
        postgresql_where=sa.text("is_published = true AND status = 'completed'"),
    )
    op.drop_table("knowledge_documents")
    op.drop_index("ix_audit_logs_target", table_name="audit_logs")
    op.drop_index("ix_audit_logs_org_created", table_name="audit_logs")
    op.drop_index("ix_audit_logs_org_actor_created", table_name="audit_logs")
    op.drop_index("ix_audit_logs_org_action_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_customer_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("sla_policies")
    op.drop_index(
        "ix_customers_name_trgm",
        table_name="customers",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_customers_external_reference"), table_name="customers")
    op.drop_index(
        "ix_customers_email_trgm",
        table_name="customers",
        postgresql_using="gin",
        postgresql_ops={"email": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_customers_email"), table_name="customers")
    op.drop_table("customers")
    op.drop_index(op.f("ix_organizations_status"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###

    # HAND-EDIT (3): drop the enum types. Every table above is gone by now, so none
    # of them is still referenced — which is what makes this the only place a single
    # pass can drop all 13, including the three shared between tables
    # (ticket_priority, processing_status, ai_operation).
    #
    # Without this, `downgrade base` leaves the types in place and the next
    # `upgrade head` fails: CREATE TYPE is not idempotent.
    #
    # The extensions are deliberately NOT dropped. They may have existed before this
    # migration ran, and another schema in the same database may be using them.
    for enum_type in (
        "ai_operation",
        "audit_action",
        "document_source_type",
        "notification_type",
        "organization_plan",
        "organization_status",
        "processing_status",
        "sender_type",
        "sentiment",
        "ticket_event_type",
        "ticket_priority",
        "ticket_status",
        "user_role",
    ):
        op.execute(f"DROP TYPE {enum_type}")
